site_name: IT in the Pharma Industry
theme:
  name: material
  palette:
    scheme: default
    primary: blue grey
  icon:
    logo: octicons/codescan-checkmark-16
  features:
    - navigation.tabs
    - navigation.tracking
    - navigation.instant
    - navigation.path
    - navigation.tracking
    - navigation.sections
    - navigation.expand
  
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - footnotes
  # This is used to enable passing CSS/HTML attributes to images etc.
  - attr_list
  # These three are used for inline text highlighting, underscoring and striking-through
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  # These two are used to enable the site-wide dictionary
  #- abbr
  #- pymdownx.snippets:
  #    auto_append:
  #      - includes/abbreviations.md

plugins:
    - mkdocs-jupyter:
        execute: True
extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/attila-vural/
    - icon: fontawesome/solid/paper-plane
      link: mailto:att.vural@gmail.com
  # This removed the "Made my mkDocs material" in the footer
  generator: false

copyright: Copyright &copy; 2022 - 2023 Attila Vural
  
nav:
    - Data Science:
        - python/DataCamp.ipynb
        # - python/index.md
        # - Page 1: python/2nd_page.md
    
    - GxP Compliance:
        - gxp/index.md    
        # - Computerized Systems: gxp/CE.md
        - Keeping in Compliance - QMS: gxp/QMS.md
            # - Overview: gxp/QMS.md
        # - Validation:
            # - System Verification: gxp/sys_verif.md
            # - Requirements to fulfill - URS: URS.md
            # - Defining the URS: defining_URS.md
            # - Defining the URS - ITRA: URS_ITRA.md
            # - Validation Deviations: VDV.md
            # - Configuration management - CS/CIL: CS.md
            # - Engineering Changes: Eng_changes.md
        
        # - Configuration Management: 
            # - Configuration Management System: CMS.md
        # - Deviation Management:
            # - Deviation Management System: DMS.md
            # - Deviations: deviations.md
        # - Change management sytem: CR_system.md
        # - Change Requests: CR.md
        - IT Risk Assessments: gxp/IT_risk.md
        # - CAPA: capa.md
    - IT/OT Security:
        - security/index.md

    # - 1:1 Teaching:
        # - 1on1/index.md

    
    