site_name: IT in the Pharma Industry
theme:
  name: material
  palette:
    scheme: default
    primary: blue grey
  icon:
    logo: octicons/codescan-checkmark-16
  features:
    - navigation.tabs
    - navigation.tracking
    - navigation.instant
    - navigation.path
    - navigation.tracking
    - navigation.sections
    - navigation.expand
  
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - footnotes
  # This is used to enable passing CSS/HTML attributes to images etc.
  - attr_list
  # These three are used for inline text highlighting, underscoring and striking-through
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  # These two are used to enable the site-wide dictionary
  #- abbr
  #- pymdownx.snippets:
  #    auto_append:
  #      - includes/abbreviations.md

plugins:
    # - mkdocs-jupyter:
        # execute: True
extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/attila-vural/
    - icon: fontawesome/solid/paper-plane
      link: mailto:att.vural@gmail.com
  # This removed the "Made my mkDocs material" in the footer
  generator: false

copyright: Copyright &copy; 2022 - 2023 Attila Vural
  
nav:
    - Compliance:
        - gxp/index.md    
        - The Regulations: gxp/regulations.md
        - Audits and Inspections: gxp/inspections.md
        # - Computerized Systems: gxp/CE.md
        - Staying in the validated state: index.md
        - Keeping in Compliance - QMS: gxp/QMS.md
            # - Overview: gxp/QMS.md
        - GxP Data?: GxP_data.md
        - GxP servers and Historians: index.md
        - Data integrity: data_integrity.md
        - ALCOA: ALCOA.md
        - Integrity: integrity.md
        - Traceability: traceability.md
        - Writing O&M SOPs: OM_SOP.md
        - Out of compliance:
            - Minor and major DVs: index.md
            - VDVs: index.md
        
        # - Configuration Management: 
            # - Configuration Management System: CMS.md
        # - Deviation Management:
            # - Deviation Management System: DMS.md
            # - Deviations: deviations.md
        # - Change management sytem: CR_system.md
        # - Change Requests: CR.md
        # - CAPA: capa.md
    - Validation projects: 
        - System Verification: gxp/sys_verif.md
        - Planning Validation Activities: gxp/validation_plan.md
        - Validation devaitions: index.md
        - FAT/SAT: FAT_SAT.md
        # - Requirements to fulfill - URS: URS.md
        # - Defining the URS: defining_URS.md
        # - Defining the URS - ITRA: URS_ITRA.md
        # - Configuration management - CS/CIL: CS.md
        # - Engineering Changes: Eng_changes.md
    - Security:
        - security/index.md
        - IT Risk Assessments:
            - Purpose: gxp/IT_risk/overview.md
            - Practical implementation: gxp/IT_risk/practical_implementation.md
            - Determining Gross Risk: gxp/IT_risk/gross_risk.md
            - Implementing controls: gxp/IT_risk/implementing_controls.md
            - Flow diagram: gxp/IT_risk/diagram.md
        - Importance of having connected equipment: security/standalone_dangers.md
        - Security Tiers: security/tiers.md
        - System types:
            - Computerized systems: CE.md
            - IT systems: IT.md
            - Low-code apps: software.md
        - Recovery Plans: 
            - The plan: TRP.md
            - RPO/RTO/WRT/MTD: RPO.md
    - OEE Metrics:
        - data/index.md
        - OEE1, OEE2 & OEE3: data/oee.md
        - OEE diagram: data/OEE_diagram.md
        - Extracting OEE data: data/oee_extract.md
        - Processing data - Alteryx: alteryx.md
        - Displaying data - Tableau: tableau.md
        - Visual Management: 
            - The 10s rule: data/10sec.md
    - Misc:
        misc/index.md
        #- Coding:
        #    - Code review: data/coding_process.md
        #- Data science case: data/DataCamp.ipynb
        # - python/index.md
        # - Page 1: python/2nd_page.md
    # - 1:1 Teaching:
        # - 1on1/index.md

    
    