site_name: IT Compliance in the Pharma Industry
extra_css:
  - stylesheets/extra.css
theme:
  name: material
  palette:
    scheme: default
    primary: blue grey
  icon:
    logo: octicons/codescan-checkmark-16
  features:
    #- navigation.tabs # This creates the top navigation bar
    - navigation.tracking
    - navigation.instant
    - navigation.path
    - navigation.tracking
    - navigation.sections
    - navigation.expand
  
markdown_extensions:
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - footnotes
  # This is used to enable passing CSS/HTML attributes to images etc.
  - attr_list
  # These three are used for inline text highlighting, underscoring and striking-through
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  # These two are used to enable the site-wide dictionary
  #- abbr
  #- pymdownx.snippets:
  #    auto_append:
  #      - includes/abbreviations.md

plugins:
    # - mkdocs-jupyter:
        # execute: True
extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/attila-vural/
    - icon: fontawesome/solid/paper-plane
      link: mailto:att.vural@gmail.com
  # This removed the "Made my mkDocs material" in the footer
  generator: false

copyright: Copyright &copy; 2022 - 2023 Attila Vural
  
nav:
    - index.md
    - GxP:
        - gxp/index.md
        - Governing regulations: gxp/regulations.md
        - GAMP: gxp/gamp.md
        - Types of findings: gxp/finding_severity.md
        - What constitutes GxP data?: gxp/gxp_data.md
        - Common documents: gxp/document_types.md
        - Common systems: gxp/common_equipment.md
        - Useful links: gxp/links.md
        #- Regulatory processes (diagram): gxp/QMS.md
    - SOPs:
        - sop/index.md 
        - Overview: sop/overview.md
        #- Relevant findings: gxp/findings.md
        # - Types of IT systems: gxp/system_types.md
        - Risk and recovery documents: gxp/IRA_TRP_OM.md
        # - GAMP5: gxp/gamp5.md
        # - GxP Data?: gxp/data.md
        # - Signature types: gxp/signature_types.md
        # - ALCOA: gxp/ALCOA.md
        # - GxP servers and Historians: gxp/serer_historian.md
        # - The validated state: gxp/validated_state.md
        # - Audits and Inspections: gxp/inspections.md
        # - Writing O&M SOPs: gxp/OM_SOP.md
        # - Data integrity: data_integrity.md
        # - Integrity: gxp/integrity.md
        # - Traceability: gxp/traceability.md
        # - Configuration Management System: gxp/CMS.md
        # - Change management sytem: gxp/CR_system.md
        # - Deviation Management System: gxp/DMS.md
        # - Minor and major DVs: gxp/dv_classification.md
        # - CAPA: gxp/capa.md
    - Risk Assessments:
        - ira/index.md
        - Example: ira/example.md
        #- Validation strategies: validation/strategies.md
        #- Typical document package: validation/document_package.md
        # - System Verification: validation/sys_verif.md
        # - Planning Validation Activities: validation/validation_plan.md
        # - Validation deviations: validation/VDV.md
        # - FAT/SAT: validation/FAT_SAT.md
    - Recovery Plans:
        - trp/index.md
    #- IT/OT Security:
        #- security/index.md
        #- IT Risk Assessments:
            # - Purpose: security/overview.md
            # - Practical implementation: security/practical_implementation.md
            # - Determining Gross Risk: security/gross_risk.md
            # - Implementing controls: security/implementing_controls.md
            #- Flow diagram: security/IT_risk/diagram.md
        # - Importance of having connected equipment: security/standalone_dangers.md
        # - Security Tiers: security/tiers.md
        # - System types:
            # - Computerized systems: security/CE.md
            # - IT systems: security/IT.md
            # - Low-code apps: security/software.md
        # - Recovery Plans: 
            # - The plan: security/TRP.md
            # - RPO/RTO/WRT/MTD: security/RPO.md
    # - OEE Metrics:
        # - data/index.md
        # - OEE1, OEE2 & OEE3: data/oee.md
        # - OEE diagram: data/OEE_diagram.md
        # - Extracting OEE data: data/oee_extract.md
        # - Processing data - Alteryx: data/alteryx.md
        # - Displaying data - Tableau: data/tableau.md
        # - Visual Management: 
            # - The 10s rule: data/10sec.md
    # - Misc:
        # misc/index.md
        #- Coding:
        #    - Code review: data/coding_process.md
        #- Data science case: data/DataCamp.ipynb
        # - python/index.md
        # - Page 1: python/2nd_page.md
    # - 1:1 Teaching:
        # - 1on1/index.md

    
    