name: ci 
on:
  push:
    branches:
      - master 
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache
      - run: pip install mkdocs-material
      # For running jupyter notebook
      - run: pip install notebook
      # For integrating jupyter notebook into mkdocs and compiling it into a static .html file
      - run: pip install mkdocs-jupyter
      # Libraries you have used in your code projects
      - run: pip install numpy
      - run: pip install pandas
      - run: pip install matplotlib
      - run: pip install seaborn
      # Compile the site into static files and push them to you gh-pages branch (overwriting existing files)
      - run: mkdocs gh-deploy --force
